sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        o+20PzZ7sVxOodA+DHOlij9gnaVDgH4RVwAEd+6/q8kYvybVgWTVdvfGqDZWMuwUJ1oRv7bCs2uoHnajIJhz2XCfeT0g4Jf+O50+Q2VidLPecoqNpbSyQ+tTPu65yqMAcewkV2cbgVq9LlET8Tt+4lr7PCe11J7wQzDT+nioTOjl6vVgGwmc6N5OIl+G73sFlzqYE908ClRaaxXUjYLfK78desyXKSLCI5tgtYCmarqOeY9seI5hQ+S/qJgdPjHnFYUFmC2ivQ1vIACwhDU1n1tdONYG/uC3apEPxkR1m9U6hqkVlav/wjHMTNf0VY8IO0gYZvuv8iGRLWJQbfI85r8HtrIR/fxewU5OAIglzflBpPb/EEtZelaqDM8nDjvXfd53VqCuVZDEUtjLlX2U0QPfAv8WC2VkL5xXAgVOOzco/yjDl5sVLoQyWzUWb6RyNwxFYVA+86I6ehSZMqp1hODkA1YuuIuZXo6gwh455LH5rHycHgX0Y7g2f89iiW3EyGmue5F2ucFRTecuo8U4pAjy++kNOhaaI7EiOGMucOjcQ6oGlNrjhmXXLzBrmsPUkytthICqHG8IVZ5GyQG7TY6qG8L7FO2Ed+LLsV6blN6QrV6XQe+5g9h8F2dp1P6Z6erhMmsucHZiA2wpy0ER3hLe9J7UJop7vpY3tTiUwrc=
    - secure: >-
        hecwhNUdi7DIuKZPwNKpDi+R+rJDIEN7nD4+g5o6guP2j+2Ljw43fE0/mldKfNMiXH0rCJzPRhtM/4TpgUmuFP3XbxnLSVzWoI+53Afl85inkm+wyaNLvE4255yEnvx/WVFy+RwuSXFssf+9mE/yGsB474i4XqISFLAi0rUpYFFDH6i4jM1bIqV+ongZAYgpiSTr17ma4hN2SUqkN1qHD/Ix+oipc7rnmEPQsGDLYXtYuuglQ76nyK/k9gRR2dvibXDSQqJfNb/Xm1+yllzuCDZM4zWBRch8Co5BVamZuZNtLIAAvj1x6QHw0oY3EwN4IZo0kq2QrESBK0qPs8EefTLdncxdTQiicW/zIMKdSJB4yG17Xfzrxez873aKsYOXM/UT9kKc1dBaQ24/M4VuZXY8CujkzBxwSf3OBFaZe9z3GzaAv9uju1mkiv9cXMlVdLrgjR1BKYkTvnCABkzRZjciHSM9kf66lb3B6JRxbC+SXQEifVJbsBnbRyGF4hwn0Z4QJySDBgB5K7Zfvw3//eRWFCqE4KHa9KHOOlCktHnF9gxiTE4JaI/dnS8ITduNR4LX5lQ3VNryTWXhwdAFSRYwJMjUv21CTCnl19BNKpzr7Lqf4/fYc/qkqZicjwQek+TTaxBX9wtob42h8uQbyg7eLiQSA+080uRQqBH3GGo=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
